on:
  push:
    branches:
        - master2



jobs:
    build:
        runs-on: ubuntu-latest


        steps:
          - name 'testing'
              run: pwd    
              - name 'testing2'
              run: echo Ahmed              


