name: Docker Workflow

on:
  push:
    branches:
      - master2  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Current Directory
        run: pwd

      - name: Print Message
        run: echo "Hello from GitHub Actions"

      - name: Login to Docker Hub
        run: |
          docker login --username mohamedelesdody --password MoJ142174#

      - name: Build Docker Image
        run: docker build -t mohamedelesdody/task-2 .

      - name: Push Docker Image
        run: docker push mohamedelesdody/task-2
